# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller 单文件绿色版打包配置。

产物： dist/AirCard.exe （单文件、无控制台、无需安装）
"""

from PyInstaller.utils.hooks import collect_submodules

hiddenimports = collect_submodules("aircard")

# PySide6 中本应用完全未使用的大型模块，剔除后可显著减小体积
excludes = [
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebEngineQuick",
    "PySide6.QtWebEngineQuickWidgets",
    "PySide6.QtWebView",
    "PySide6.QtWebSockets",
    "PySide6.QtHttpServer",
    "PySide6.QtQuick",
    "PySide6.QtQuick3D",
    "PySide6.QtQuickWidgets",
    "PySide6.QtQml",
    "PySide6.QtQmlCore",
    "PySide6.QtQmlModels",
    "PySide6.QtQmlNetwork",
    "PySide6.QtQmlWorkerScript",
    "PySide6.QtQmlXmlListModel",
    "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets",
    "PySide6.QtCharts",
    "PySide6.QtDataVisualization",
    "PySide6.QtGraphs",
    "PySide6.QtGraphsWidgets",
    "PySide6.Qt3DCore",
    "PySide6.Qt3DRender",
    "PySide6.Qt3DInput",
    "PySide6.Qt3DLogic",
    "PySide6.Qt3DAnimation",
    "PySide6.Qt3DExtras",
    "PySide6.QtBluetooth",
    "PySide6.QtNfc",
    "PySide6.QtPositioning",
    "PySide6.QtPositioningQuick",
    "PySide6.QtSerialPort",
    "PySide6.QtSensors",
    "PySide6.QtSvgWidgets",
    "PySide6.QtSpatialAudio",
    "PySide6.QtTextToSpeech",
    "PySide6.QtRemoteObjects",
    "PySide6.QtScxml",
    "PySide6.QtStateMachine",
    "PySide6.QtTest",
    "PySide6.QtDesigner",
    "PySide6.QtUiTools",
    "PySide6.QtHelp",
    "PySide6.QtOpenGLWidgets",
    "PySide6.QtPdf",
    "PySide6.QtPdfWidgets",
    "PySide6.QtSql",
    "PySide6.QtNetworkAuth",
    "PySide6.QtWebChannel",
    "PySide6.QtQuickControls2",
    "PySide6.QtQuickTest",
    "PySide6.QtConcurrent",
    "PySide6.QtDBus",
    "PySide6.QtAxContainer",
    "tkinter",
    "unittest",
    "pydoc",
    "doctest",
    "lib2to3",
    "numpy",
    "matplotlib",
    "scipy",
    "pandas",
    "IPython",
    "notebook",
    "pytest",
]

block_cipher = None

a = Analysis(
    ["AirCard.py"],
    pathex=["."],
    binaries=[],
    datas=[("assets/aircard.ico", "assets"), ("assets/aircard.png", "assets")],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="AirCard",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="assets/aircard.ico",
    version=None,
)
